In [47]:
import numpy as np

In [48]:
import pandas as pd

In [49]:
df = pd.read_csv('student.csv',usecols=['hours_studied','attendance_percent','exam_score' ])

In [50]:
import plotly.express as px

In [51]:
import  plotly .graph_objects as go

In [52]:
df.head(2)

hours_studied  attendance_percent  exam_score
0            8.0                72.1        30.2
1            1.3                60.7        25.0

In [53]:
x = df.iloc[:,0:2]

In [54]:
x.head(2)

hours_studied  attendance_percent
0            8.0                72.1
1            1.3                60.7

In [55]:
y = df.iloc[:,-1]

In [56]:
y.head(2)

0    30.2
1    25.0
Name: exam_score, dtype: float64

In [57]:
fig = px.scatter_3d(df,x='hours_studied',y='attendance_percent',z='exam_score')

In [58]:
fig.show()

In [59]:
from sklearn .model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=3)

In [61]:
x_train

hours_studied  attendance_percent
156            4.7                56.1
115           10.6                91.6
155            3.5                80.0
15             7.0                51.2
61             8.0                64.3
..             ...                 ...
0              8.0                72.1
184            5.4                94.1
131            1.6                83.5
152            5.8                55.1
106            2.2                56.8

[160 rows x 2 columns]

In [62]:
y_train.shape

(160,)

In [63]:
y_test.shape

(40,)

In [64]:
df.isnull().sum()

hours_studied         0
attendance_percent    0
exam_score            0
dtype: int64

In [65]:
from sklearn .linear_model import LinearRegression

In [66]:
lr = LinearRegression()

In [67]:
x_train.shape

(160, 2)

In [68]:
y_train.shape

(160,)

In [69]:
x_test.shape

(40, 2)

In [70]:
lr.fit(x_train,y_train)

LinearRegression()

In [71]:
y_pred = lr.predict(x_test)

In [72]:
y_pred

array([38.9387042 , 30.23946394, 25.1780949 , 24.76749385, 43.31502505,
       34.82542661, 24.52156419, 28.11164948, 28.33683199, 25.89678834,
       34.81930788, 42.91153369, 29.73206394, 34.6575307 , 28.16306896,
       41.95409899, 33.0309188 , 31.46613933, 28.63326887, 28.74131431,
       35.12666093, 38.29118642, 26.51190346, 38.9516023 , 44.83582505,
       35.75731673, 38.42320353, 40.16471894, 35.46931083, 42.84614643,
       40.70378225, 30.20838257, 30.78662792, 32.1135784 , 40.56010963,
       36.30935685, 40.16149442, 40.49959851, 26.80247323, 29.86573266])

In [73]:
from sklearn .metrics import mean_absolute_error,mean_squared_error,r2_score

In [74]:
print("MAE",mean_squared_error(y_test,y_pred))

MAE 15.29978609147904


In [75]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 3.314159405930796


In [76]:
print("r2",r2_score(y_test,y_pred))

r2 0.6911277119427055


In [77]:
x= np.linspace(-5,5,10)

In [78]:
x

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [79]:
y = np.linspace(-5,5,10)

In [80]:
xGrid,yGrid = np.meshgrid(y,x)

In [81]:
m = lr.coef_

In [82]:
m

array([1.65992682, 0.1132519 ])

In [83]:
b= lr.intercept_

In [84]:
b

14.886139604360935

# y = mx+b

In [86]:
m*4.7+b

array([22.68779564, 15.41842354])